### PR TITLE
Make List own its container node

### PR DESCRIPTION
**Pull request by anttisykari**
A sketch of `list`that owns the DOM node containing its children.

### CODE REVIEW

**Comment by pakastin** [comment]
That's actually a really good idea!

**Comment by pakastin** [comment]
Although now the list works by itself:
```
class Item {
  constructor () {
    this.el = el('item');
  },
  update ({ name }) {
    this.el.textContent = name;
  }
}
var list = new List(Item, '_id');
list.update([{ _id: 1, name: 'foo' }, { _id: 2, name: 'bar' }]);
console.log(list.views) // <item>foo</item><item>bar</item>
mount(document.body, list.views);
```
..that would break that

**Comment by anttisykari** [comment]
True... Though you could make List behave so that the parent element is not needed

    list = new List(null, Item, '_id')

And perhaps if `this.el` is null and and the list gets mounted, then set `this.el` from the parent element and do a setChildren.

That might be confusing if you're not intimate with List's internals, though.

**Comment by anttisykari** [comment]
You should probably be able to give list a node as the first argument:

```list('ul', Item);

var ul = el('ul');
list(ul, Item); // should work too

**Comment by anttisykari** [comment]
Now you can do:

```
      class Item {
        constructor () {
          this.el = el('item');
        }
        update ({ name }) {
          this.el.textContent = name;
        }
      }
      var list = new List(null, Item, '_id');
      list.update([{ _id: 1, name: 'foo' }, { _id: 2, name: 'bar' }]);
      console.log(list.views); // <item>foo</item><item>bar</item>
      mount(document.body, list.views);
```

**Comment by anttisykari** [comment]
This also seems to make the Table example a good deal simpler (although I did have to change the `update` function to take `[[ 1, 2, 3 ]]` instead of `{ tbody: [[ 1, 2, 3 ]] }`: 

https://github.com/pakastin/redom/pull/23/commits/8047eb9f437ad5eddae7e8c41a99aea8a6a8ba6f

**Comment by pakastin** [comment]
Another thing is that if you want to do:
```js
el('todo-app',
  el('ul.items',
    list(Item, '_id')
  )
)
```
..you would need to create a new reference for that list?

**Comment by pakastin** [comment]
Why do you need a reference to the parent?

**Comment by pakastin** [comment]
What if you had `list.mount(parent)` -method? Then mounting would be `list`'s responsible, not `el`'s or `mount`'s..

**Comment by pakastin** [comment]
We talked on Slack in Finnish about this. This is probably a "notfix" because it doesn't help with your issue of having elements before and after the list.

**Comment by pakastin** [comment]
..I add the label for now, but will investigate your issue in the next version

**Comment by anttisykari** [comment]
My real issue isn't really that I'd want `el(), list(), el()` - just that if someone tries to do that with the current list, confusion might ensue.

In summary, the benefits of the kind of `list` in this PR (`list(el, Item)`) are:

- make this kind of pattern unnecessary:

```
var List = view({
  init () {
    this.el = el('ul',
      this.list = list(Item, 'id')
    )
  },
  update (data) {
    this.list.update(data);
  }
});
```
(Can be replaced with `function List () { return list('ul', Item', 'id' }`)

**Comment by pakastin** [comment]
Let's see how everything works out in the new version..

**Comment by maciejhirsz** [comment]
> My real issue isn't really that I'd want `el(), list(), el()` - just that if someone tries to do that with the current list, confusion might ensue.

I can second that notion.

Defining a list with a DOM `Node` would make a lot of sense. I remember playing around with FRZR dbmon and putting a `List(Cell)` as a 3rd child in the `Row`, expecting the children coming from the list to be appended to the parent - they were, but the other children also got removed. 

The functionality of list updating child nodes according to the array of data is fine, the fact that it does it on the parent node breaks the ownership scope though.

**Comment by pakastin** [comment]
In the new version there could be:
```js
  list('.todo-items', '.todo-item')
```

..and you could update the data with:
```
init () {
  this.items = this.find('.todo-items');
}
update (data) {
  this.items.update(data.items);
}
```

**Comment by pakastin** [comment]
If you want to update the "parent", you could do it like:
```js
this.items.el.classList.add('red');
```

..so it would work like a component!

**Comment by pakastin** [comment]
That will actually make the logic of `list` so much simplier.. 👍

**Comment by pakastin** [comment]
Let's see if this gets released, but will need to update examples first if..

**Comment by hville** [comment]
Regarding this issue and #24, would it be easier to just have another `class` instead of bending `List` to fit so many use cases? Something like:
```javascript
table = new Template('table', [headView, bodyView, footView])
table.update([headData, bodyData, footData])
```
This would retain the power of `List` without any hacks to retain the relative position to other siblings.

**Comment by pakastin** [comment]
Basically that's just what I do already.. You can (and should) wrap head to `<thead>` and body to `<tbody>` anyway. Not sure about that footer though.. But you can use for example `.concat` if you need both of them inside body.

**Comment by pakastin** [comment]
When I create tables I usually use classes something like this:
```js
class Users {
  constructor () {
    this.el = el('table.users',
      this.usersHead = el('thead', 
        el('tr',
          ['First name', 'Last name', 'Actions'].map(field => el('td', field))
        )
      ),
      this.users = list('.tbody', User, '_id')
    )
  }
  update ({ users } = {}) {
    this.users.update(users || [])
  }
}
```

**Comment by hville** [comment]
Super thanks for the prompt reply. 

My example was bad because it did not fully illustrate what I was trying to explain. 

This might be a better example:
```
row = new Template('tr', [Checkbox, ValueCell, SumCell])
row.update([[true], [1,2,3], [6]])
```

Thing is, as much as I like `redom` conceptually, exceptions creep in (different sibling, selected items, input cells) and the list of exceptions brings me back to manual rebuilding and re-assigning children.

I'll leave it at that since it is diverging from the main topic of this issue.

**Comment by pakastin** [comment]
oh, I see.. You can actually create different types for different indexes.

Here's an example:
https://github.com/lhorie/frzr-dbmon/blob/gh-pages/frzr/app.js#L20-L50

😉

**Comment by pakastin** [comment]
I would probably do it like this though:
```
class Template {
  constructor () {
    this.checkbox = new Checkbox()
    this.valueCell = new ValueCell()
    this.sumCell = new SumCell()
  }
  update ([ checkbox, valueCell, sumCell ]) {
    this.checkbox.update(checkbox)
    this.valueCell.update(valueCell)
    this.sumCell.update(sumCell)
  }
}
```

**Comment by pakastin** [comment]
btw. you can also use `setChildren`:
```
setChildren(this,
  checkBoxes.concat(valueCells).concat(sumCells)
)
```

It's not that hard to keep lookup of references..

**Comment by pakastin** [comment]
Here's an example of keeping a lookup of HTMLElement references:
https://jsfiddle.net/pakastin/6uLg38fu/

**Comment by pakastin** [comment]
BUT I've thought about having some kind of templating support.. Let's see....

**Pull request merged**
