### PR TITLE
fixes #58

### PR DESCRIPTION
**Pull request by pakastin**

### CODE REVIEW

**Comment by pakastin** [comment]
@tomerigal: 
- First of all, thank you so much for contribution! 👍
- There was a bug when mounting view to element. 😳
- Why should `unmount` trigger reversed? 🤔

**Comment by pakastin** [comment]
I'm going to merge this for now, but let me know what's your view on reversed `unmount`..

**Comment by tomerigal** [comment]
@pakastin 
also onmount should trigger reversed.
i think component lifecycle events need to be triggered after childrens triggered.
Example:
```js
class Hello {
    onmount() {
        this.hello.baboom = function () { alert("") };
    }
}
class App {
    constructor() {
        this.el = el('app',
            this.hello = new Hello()
        );
    }
    onmount() {
        // this.hello not mounted yet?
        this.hello.baboom();
        // baboom is not a function
    }
}
```

**Comment by talmobi** [comment]
@tomerigal 
I think you confused `onmount` with `unmount` in that example. Your code/tests have the correct idea that mounting lifecycle events should trigger Top -> Down (so that children can rely on their parents being mounted first).

The question here is now with unmounting. Traditionally they would trigger in reverse in respect to mounting aka Down -> Top (or Inside -> Out). Again, your code/tests have the right idea (I had similar tests commented out in favor of how RE:DOM actually unmounts).

The mounting phase is usually used as an initialization or setup step: AJAX calls, timers, intervals, DOM manipulation, third party library initialization etc and the unmounting phase is usually done to clean up these tasks setup/initialized in the mounting phase (clearing intervals, ajax calls, cleaning the DOM, third party library cleanup).

Essentially with `onmount` (after mount) you could rely on that the element is in the DOM and with `onunmount` (before unmount) you could also rely on that the element is in the DOM.

But I'm not entirely sure if the latter (`onunmount`) would have undesired side-effects even with a Top-Down order instead of Down->Top (and therefore could not rely on that the element is in the DOM during the lifecycle event) outside of extremely contrived examples.

One thing that comes to mind is if a child, responsible of its own cleanup when getting unmounted, would try to clean up undefined values if the parent would have previously cleaned up a larger area that included the child's responsible area. However, I think this may be an extremely contrived example developed using blatant anti-patterns.

**Comment by pakastin** [comment]
I agree with you @talmobi.

**Comment by pakastin** [comment]
Btw. even if you trigger `unmount` from top–>down, parent–child references still exist since they are not really unmounted from each other (only the upmost child will unmount from it's parent after the event).

**Pull request merged**
