### PR TITLE
component can be used as list parent

### PR DESCRIPTION
**Pull request by tomerigal**
Example:
```javascript
class Li {
  constructor () {
    this.el = el('li');
  }
  update (i) {
    this.el.textContent =  `Item ${i}`;
  }
}

class Ul{
  constructor (){
      this.el = el('ul');
  }
  pop(){
    //...
  }
  update(){
      list(this, Li).update(...arguments);
  }
}
var ul = new Ul(); // Ul component

// new list with Ul component as list parent
const ulContainer = list(ul, Li);
ulContainer.update([1, 2, 3]);
ul.update([1, 2, 3, 4]);
ul.pop();

mount(document.body, ul);
```

### CODE REVIEW

**Comment by pakastin** [comment]
That's perfect, thanks! 👍

Would you like to join our Slack group? Go an visit http://koodiklinikka.fi write your email there and press enter. Then join #redom @ koodiklinikka.slack.com

**Comment by pakastin** [comment]
Released (v1.14), thank you for contribution! 😎👍

**Comment by tomerigal** [comment]
Thank you for the quick response and release!
I'll consider joining the Slack group once I have more available time... :)

**Comment by pakastin** [comment]
Haha, ok 😎

**Pull request merged**
