### PR TITLE
Benchmark!

### PR DESCRIPTION
**Pull request by maciejhirsz**
`npm run build-bench`, then open `bench/index.html`, preferably with dev tools already open. This will freeze on firefox without electrolysis and will generally make tabs unresponsive while the benchmark is running.

### CODE REVIEW

**Comment by pakastin** [comment]
Thanks! I'll take a look of this in the morning..I didn't sleep that much last night designing redom all night 😁

**Comment by maciejhirsz** [comment]
Will make a new PR later with fixed benches now that I've reset my branch to your `dev`.

**Comment by pakastin** [comment]
I'm still not sure whether this separate branch is good or not..

**Comment by maciejhirsz** [comment]
I guess for normal patch work using `master` is fine, in all other OS contributions I did I typically PR against `master`. Alternative branches are good for longer ongoing refactors and such.

**Comment by pakastin** [comment]
I suck with git so bad. I need to learn how to "synchronize" branches..

**Pull request closed without merging**
